### ISSUE TITLE
Role base volume pricing not working

### ISSUE THREAD

**Issue by hkleow** [solidusio-contrib/solidus_volume_pricing#47]
<img width="1075" alt="Screen Shot 2020-02-24 at 1 05 28 PM" src="https://user-images.githubusercontent.com/15167345/75129901-6db1a380-5706-11ea-9b60-c9ac218efb29.png">
<img width="1280" alt="Screen Shot 2020-02-24 at 1 04 53 PM" src="https://user-images.githubusercontent.com/15167345/75129904-70ac9400-5706-11ea-8e1d-b9bde6a2f4d2.png">
<img width="1052" alt="Screen Shot 2020-02-24 at 1 05 45 PM" src="https://user-images.githubusercontent.com/15167345/75129906-74401b00-5706-11ea-9d3b-ec5e012ad13f.png">

as u can see here, i've set my Roles Bronze and set the volume pricing to roles of bronze only. but updating the quantity in carting doesnt seem to be reducing the price as shown. any ideas how i can fix this? 

i am also using this gem, for role creation
https://github.com/boomerdigital/solidus_user_roles

**Comment by aldesantis** [comment]
@hkleow are you using the latest master of solidus_volume_pricing? [A PR was recently submitted](https://github.com/solidusio-contrib/solidus_volume_pricing/pull/46) to fix precisely this use case.

**Comment by hkleow** [comment]
so i just need to revert to that version it would work? because for my use case, my client wants to specify membership tier along with volume pricing.
Example role user with bronze, silver, gold, diamond
each of those will have different pricing

**Comment by hkleow** [comment]
Managed to fix it just by updating to latest gem
`gem 'solidus_volume_pricing', git: "https://github.com/solidusio-contrib/solidus_volume_pricing"
`
before this i was just using, maybe u should also update ruby gem. anyway thanks for this, works great now! 
`gem 'solidus_volume_pricing',`
