### ISSUE TITLE
Rails v 5.0.1

### ISSUE THREAD

**Issue by winterblack** [solidusio-contrib/solidus_volume_pricing#8]
Any chance this can get updated for Rails v 5.0.1. Are there compatibility issues with the latest version of Solidus?

**Comment by mamhoff** [comment]
It doesn't run right now with Solidus > 2 and Rails 5. We'll eventually get around to porting it, but it doesn't have super high priority for us right now. We'll happily accept a pull request though.

**Comment by seand7565** [comment]
#11 should close this

**Comment by tvdeyen** [comment]
This is now tested with Solidus >= 2.4 and therefore with Rails 5.1
